🏠  Home page design
aweandreverence/www.theology101.church pull request #12
Opened 2023-12-14 20:46 UTC by Pinimes

## Status 
WIP

## Description
Enhanced the home page's user interface for Theology 101 website and incorporated a showcase picture.

## Screenshot
![homepage](https://github.com/aweandreverence/www.theology101.church/assets/144367037/54b43ec2-9481-45d3-ac8d-27e5255929c3)

2023-12-15 01:14 UTC, jontsai requested changes

2023-12-15 01:14 UTC, jontsai commented on styles/common.module.scss
> +        font-family: cursive;
Not sure why this is showing Comic Sans. Let's pick someone from https://fonts.google.com/

2023-12-15 21:39 UTC, jontsai approved these changes
LGTM

2023-12-15 22:27 UTC, YosefAshenafi approved these changes
LGTM

2023-12-15 22:54 UTC, lleung030 approved these changes
LGTM

2023-12-16 06:29 UTC, goztrk requested changes

2023-12-16 06:29 UTC, goztrk commented on pages/_app.jsx
> +    const isHomePage = router.pathname === '/';
This is being repeated in two places so it is not DRY.

To make it DRY, we need to create a custom hook (it is actually a function this time but hooks are a special trait of React)

- Create a file named `utils/hooks.js`
- Put the following code inside it:

```js
import { useRouter } from 'next/router';

function useIsHomePage() {
    const router = useRouter();
    return router.pathname === '/';
}
```

Then you can use this function/hook here:
```suggestion
    const isHomePage = useIsHomePage();
```

Don't forget to add `import { useIsHomePage() } from '@utils/hooks';`.
Also, Remove the unused `useRouter` import.

2023-12-16 06:29 UTC, goztrk commented on pages/_app.jsx
> +    );
This is not correct usage. If you do not use `BaseLayout` component, the header definitions on `BaseLayout` (meta, favicon, font-awesome, google, analytics) will not be applied to the homepage.

First let's change this to:

```suggestion
    return isHomePage ? (
        <BaseLayout hideSidebar={isHomePage}>{getLayout(<Component {...pageProps} />)}</BaseLayout>
    );
```

Then in `components/base_layout.jsx`:

```jsx
...
export function BaseLayout({ hideSidebar }) {
...
                           <div className={hideSidebar ? "col-12" : "col-lg-9 col-md-8"}>{children}</div>
{!hideSidebar && (
                           <div className="col-lg-3 col-md-4">
                                <div className="bg-light text-dark w-100 p-3">
                                    <SidebarList
                                        title="Topics"
                                        url="topics"
                                        entries={topics}
                                    />
                                    <SidebarList
                                        title="Tags"
                                        url="tags"
                                        entries={tags}
                                    />
                                </div>
                                <a
                                    href="https://theology101ak.thinkific.com/courses/howtostudythebible?ref=6431a0"
                                    target="_blank"
                                >
                                    <img className="img-fluid" src="/ad.png" />
                                </a>
                            </div>
)}
```
With this, we made the sidebar dynamic. We can disable showing it with a prop depending on the page.

2023-12-16 06:29 UTC, goztrk commented on pages/index.jsx
Revert the head changes on this page, please. See the comment above.

2023-12-18 21:54 UTC, goztrk approved these changes
LGTM

2023-12-19 05:58 UTC, merged