Update footer year
aweandreverence/www.theology101.church pull request #4
Opened 2023-11-20 15:55 UTC by Pinimes

## Status
Ready

## Description
Update footer year for Theology101 website

## Screenshot
![image](https://github.com/aweandreverence/www.theology101.church/assets/144367037/bdd5647c-736c-40d6-82ed-fb60a349895e)

2023-11-21 16:01 UTC, jontsai approved these changes
LGTM

2023-11-21 16:02 UTC, jontsai requested changes
Theology101 was created in 2023. Let’s keep it 2023.

You need to write code so that the footer will display the correct value next year (2 months from now, in 2024)

2023-11-22 16:56 UTC, jontsai requested changes

2023-11-22 16:56 UTC, jontsai commented on components/footer.js
> +    const YEAR_CREATED = '2023';
This value should go somewhere in a `constants.js`, not in this file. You should test that this code works by temporarily setting it to something in the past, like `2020`.

2023-11-22 16:56 UTC, jontsai commented on components/footer.js
> +                        {YEAR_CREATED != CURRENT_YEAR ? - CURRENT_YEAR : ''}
```suggestion
                        &copy; Awe and Reverence {YEAR_CREATED}
                        {YEAR_CREATED != CURRENT_YEAR ? ` - ${CURRENT_YEAR}` : ''}
```

- Put the space inside the conditional, not outside of it
- Without this, it would display a negative number, like `2020 -2023` (your original code) for different years of `2023 ` for same year (extra trailing space); mine would do `2020 - 2023` (correct — 1 space on both sides) for different years or `2023` (for same year, no extra trailing space)

2023-11-22 21:21 UTC, YosefAshenafi approved these changes
LGTM

2023-11-22 22:43 UTC, jontsai approved these changes
LGTM

2023-11-22 22:43 UTC, jontsai commented on constants/date.js
> +export const CURRENT_YEAR = new Date().getFullYear();
A bit on the fence for having a constant that does this, but it seems fine for now.

2023-11-22 22:45 UTC, lleung030 approved these changes
LGTM

2023-11-23 07:26 UTC, merged