✨ Update sidebar User Interface
aweandreverence/www.theology101.church pull request #5
Opened 2023-11-21 16:42 UTC by Pinimes

## Status
WIP

## Description
- Sample user interface update for the sidebar

## Screenshot
![sidebar](https://github.com/aweandreverence/www.theology101.church/assets/144367037/9c15936c-4481-4f54-8a98-12df7daedbcd)

2023-11-24 03:05 UTC, jontsai requested changes

2023-11-24 03:05 UTC, jontsai commented on components/tags.js
> +    getYouTubeThumbnail = async (videoId, tag) => {
This function is defined in two files, so it should probably just be defined in a single place (3rd file) instead, and imported in the two file.

This is the very important SWE principle called DRY:
https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

2023-11-24 03:05 UTC, jontsai commented on components/tags.js
> +          const apiUrl = `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`;
I'm not sure if it makes sense to do a live call for each thumbnail, as it adds to the processing time to load the page.

Ideally, we update the Python script used to generate the JSON file, to fetch the thumbnail images at that time.

2023-11-24 19:02 UTC, Pinimes commented on components/tags.js
> +          const apiUrl = `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`;
Okay, would it be acceptable to manually insert the generated thumbnail URLs into THEOLOGY101_DATA JSON?

2023-11-24 19:02 UTC, Pinimes commented on components/tags.js
> +    getYouTubeThumbnail = async (videoId, tag) => {
done

2023-12-08 19:40 UTC, lleung030 approved these changes
LFTM

2023-12-08 20:57 UTC, goztrk requested changes

2023-12-11 20:24 UTC, Pinimes commented on components/base_layout.jsx
> +import styles from 'styles/common.module.scss';
done

2023-12-11 20:25 UTC, Pinimes commented on components/base_layout.jsx
>  function SidebarList({ title, entries, url }) {
done

2023-12-11 20:25 UTC, Pinimes commented on styles/sidebar.module.scss
> +        height: 500px;
reverted.

2023-12-11 21:14 UTC, goztrk requested changes
Code wise it is fine but as UI perspective it is not good enough.

- The video count is not consistent.
- The sidebar is too long. It would be ok If we had that long content but we don't.

2023-12-13 07:36 UTC, goztrk reviewed
LFTM for now.

But the design is still not enough. The sidebar is still too long. Could you please file a Trello card and work on it after this PR got merged?

- First come up with design ideas.
  - It does not have to be the same design. Maybe a nice way to show all Topics in the homepage?
  - Check ThemeForest for inspiration.
  - Consider the option of not using Sidebar at all?
  - Or maybe when user opens a video page we can only show videos from the same topic on the sidebar. Just like YouTube Playlists.

2023-12-13 07:36 UTC, goztrk approved these changes

2023-12-13 11:59 UTC, YosefAshenafi approved these changes
LGTM

2023-12-14 07:05 UTC, jontsai approved these changes
LGTM

2023-12-14 07:05 UTC, merged